name: Set Up PHP Tests
description: Sets up PHP and dependencies for testing

inputs:
  php_version:
    description: PHP version to use
    required: true
  COMPOSER_TOKEN:
    description: The GitHub Actions token for Composer to use
    required: true

runs:
  using: 'composite'

  steps:
    - name: Configure time zones
      shell: bash
      run: sudo timedatectl set-timezone Europe/London

    - name: Set up PHP
      id: setup-php
      uses: shivammathur/setup-php@0f7f1d08e3e32076e51cae65eb0b0c871405b16e # v2.34.1
      with:
        php-version: ${{ inputs.php_version }}
        ini-values: error_reporting=E_ALL, date.timezone=Europe/London, max_execution_time=120
        tools: composer
        extensions: zip, mbstring, pdo, pdo_mysql, bcmath, ctype, fileinfo, json, tokenizer, xml
        coverage: none
      env:
        GITHUB_TOKEN: ${{ inputs.COMPOSER_TOKEN }}

    - name: Set env
      shell: bash
      run: |
        echo "PATH=~/.config/composer/vendor/bin:$PATH" >> $GITHUB_ENV
        echo "ENVIRONMENT=github" >> $GITHUB_ENV

    - name: Configure Composer
      shell: bash
      env:
        COMPOSER_TOKEN: ${{ inputs.COMPOSER_TOKEN }}
      run: composer config --global github-oauth.github.com "$COMPOSER_TOKEN"

    - name: Get composer cache directory
      shell: bash
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache composer dependencies
      uses: actions/cache@v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-php-${{ inputs.php_version }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-php-${{ inputs.php_version }}-

    - name: Install PHP dependencies
      shell: bash
      run: composer install --prefer-dist --no-progress --no-interaction
